Makes use of std::move to solve issue to the errors present on ln 55
../src/dvhop/model/distance-table.cc:55:59: error: cannot bind rvalue reference of type ‘double&&’ to lvalue of type ‘double’
   55 |           info.SetPosition (std::make_pair<double,double>(xPos, yPos));
      |                                                           ^~~~


Possibly just a temporary fix